auto_pickup_drops: false
suppress_block_drop_on_custom_drop: true

ore-removal:
  # If disabled, no changes will be made to the world generation
  enabled: false
  # Global settings for all worlds excluding overrides
  global:
    # If true, by default all ores will be removed from the world generation
    default: true
    # Override for the default value of a specific ore
    # accepted keys are:
    # COAL_ORE, COPPER_ORE, IRON_ORE, GOLD_ORE, DIAMOND_ORE, REDSTONE_ORE, LAPIS_ORE, EMERALD_ORE
    # DEEPSLATE_COAL_ORE, DEEPSLATE_COPPER_ORE, DEEPSLATE_IRON_ORE, DEEPSLATE_GOLD_ORE, DEEPSLATE_DIAMOND_ORE, DEEPSLATE_REDSTONE_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_EMERALD_ORE
    # NETHER_GOLD_ORE, NETHER_QUARTZ_ORE, ANCIENT_DEBRIS
    NETHER_GOLD_ORE: false
    NETHER_QUARTZ_ORE: false
    ANCIENT_DEBRIS: false
  # Overrides for specific worlds
  overrides:
    world_the_end:
      default: false
    world_nether:
      default: false
      NETHER_GOLD_ORE: true
      NETHER_QUARTZ_ORE: true
      ANCIENT_DEBRIS: true

blocks:
  stone:
    drop: cobblestone
  deepslate:
    drop: cobbled_deepslate

veins:
  cooldown: 5s
  vein_base_chance: 0.482
  token_window: 20s
  token_range: 8
  enchant_modifiers:
    fortune:
      vein_chance_mult: 0.05
    looting:
      vein_chance_mult: 0.02
    luck:
      vein_chance_mult: 0.03
    unluck:
      vein_chance_mult: -0.05
  vein_start_sound:
    sound: "BLOCK_BEACON_POWER_SELECT"
    volume: 1.0
    pitch: 1.0

drops:
  - item: coal
    chance: 0.0069
    min_y: 0
    max_y: 320
    fortune_multiplier: true
    tool_tiers: [WOODEN_PICKAXE, STONE_PICKAXE, COPPER_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 20
    exp_drop: 2

  - item: raw_copper
    chance: 0.0043
    min_y: -16
    max_y: 112
    fortune_multiplier: true
    tool_tiers: [COPPER_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 10
    exp_drop: 2

  - item: raw_iron
    chance: 0.0040
    min_y: -64
    max_y: 320
    fortune_multiplier: false
    tool_tiers: [COPPER_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 12
    exp_drop: 0

  - item: raw_gold
    chance: 0.0022
    min_y: -64
    max_y: 32
    fortune_multiplier: false
    tool_tiers: [IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 10
    exp_drop: 0

  - item: redstone
    chance: 0.0020
    min_y: -64
    max_y: 16
    fortune_multiplier: true
    tool_tiers: [IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 8
    exp_drop: 1

  - item: lapis_lazuli
    chance: 0.0011
    min_y: -64
    max_y: 64
    fortune_multiplier: true
    tool_tiers: [COPPER_PICKAXE, IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 6
    exp_drop: 5

  - item: diamond
    chance: 0.0008
    min_y: -64
    max_y: 16
    fortune_multiplier: true
    tool_tiers: [IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 8
    exp_drop: 7

  - item: emerald
    chance: 0.0006
    min_y: -16
    max_y: 320
    fortune_multiplier: true
    tool_tiers: [IRON_PICKAXE, GOLDEN_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
    vein_max_size: 2
    exp_drop: 7

  # Example command drop (percentage chance only, not affected by enchantments/veins/XP)
  # You can specify whether you want the command to be executed by the player, or console using "player:" and "console:"
  # If you don't specify what it will run as, it will default to what you have execute_as set to
  - type: command
    commands:
      - "player:say I rolled a player-level bonus!"
      - "console:say %player% rolled a server-level bonus!"
      - "give %player% diamond 1"
    chance: 0.0005
    min_y: -64
    max_y: 320
    execute_as: console